import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    UpdateDateColumn,
    ManyToOne,
    JoinColumn,
    Unique,
} from 'typeorm';
import { Question } from './questions.entity';

export enum ImageStatus {
    NONE = 'none',
    PENDING = 'pending',
    PROCESSING = 'processing',
    COMPLETED = 'completed',
    FAILED = 'failed',
}

export enum OptionLetter {
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
}

@Entity('question_options')
@Unique('uk_question_option', ['questionId', 'optionLetter'])
export class QuestionOption {
    @PrimaryGeneratedColumn({
        type: 'bigint',
        unsigned: true,
    })
    id: number;

    @Column({
        name: 'question_id',
        type: 'bigint',
    })
    questionId: number;

    @ManyToOne(() => Question, {
        onDelete: 'CASCADE',
    })
    @JoinColumn({ name: 'question_id' })
    question: Question;

    @Column({
        name: 'option_letter',
        type: 'enum',
        enum: OptionLetter,
    })
    optionLetter: OptionLetter;

    @Column({
        name: 'option_text',
        type: 'text',
    })
    optionText: string;

    @Column({
        name: 'isCorrect',
        type: 'tinyint',
        width: 1,
        default: 0,
        comment: '1 = Correct Answer, 0 = Incorrect Distractor',
    })
    isCorrect: number;

    @Column({
        name: 'requires_image',
        type: 'tinyint',
        width: 1,
        default: 0,
    })
    requiresImage: number;

    @Column({
        name: 'image_prompt',
        type: 'text',
        nullable: true,
        comment: 'Generated by AI if option text needs visual answers',
    })
    imagePrompt: string;

    @Column({
        name: 'image_url',
        type: 'varchar',
        length: 2048,
        nullable: true,
    })
    imageUrl: string;

    @Column({
        name: 'image_status',
        type: 'enum',
        enum: ImageStatus,
        default: ImageStatus.NONE,
    })
    imageStatus: ImageStatus;

    @CreateDateColumn({
        name: 'createdAt',
        type: 'timestamp',
    })
    createdAt: Date;

    @UpdateDateColumn({
        name: 'updatedAt',
        type: 'timestamp',
    })
    updatedAt: Date;
}