import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

export enum ImageStatus {
  NONE = 'none',
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export enum ReviewStatus {
  DRAFT = 'draft',
  APPROVED = 'approved',
  REJECTED = 'rejected',
}

@Entity('questions')
@Index('idx_grade_subject_term', ['displayGrade', 'subjectId'])
@Index('idx_competency', ['competencyTargetedId'])
export class Question {
  @PrimaryGeneratedColumn({
    type: 'bigint',
    unsigned: true,
  })
  id: number;

  @Column({
    type: 'int',
    comment: 'The grade selected by the user/admin (e.g., Grade 3)',
  })
  displayGrade: number;

  @Column({
    type: 'int',
    comment:
      'The actual curriculum standard grade used for content difficulty (e.g., Grade 2 for fallback)',
  })
  syllabusGrade: number;

  @Column({
    type: 'int',
    comment: 'Relational mapping to your subjects table',
  })
  subjectId: number;

  @Column({
    type: 'bigint',
    comment: 'Foreign key link to competencymaster',
  })
  competencyTargetedId: number;

  @Column({
    type: 'text',
    comment: 'Stores raw question content embedded with semantic HTML tags',
  })
  questionText: string;

  @Column({
    type: 'tinyint',
    width: 1,
    default: 0,
    comment: '0 = False, 1 = True (Assigned by Gemini)',
  })
  requiresImage: number;

  @Column({
    type: 'text',
    nullable: true,
    comment:
      'Detailed descriptive prompt generated by AI for text-to-image engine workflows',
  })
  imagePrompt: string;

  @Column({
    type: 'varchar',
    length: 2048,
    nullable: true,
    comment:
      'Public URL pointing to cloud storage where image is hosted once compiled',
  })
  imageUrl: string;

  @Column({
    type: 'enum',
    enum: ImageStatus,
    default: ImageStatus.NONE,
  })
  imageStatus: ImageStatus;

  @Column({
    type: 'tinyint',
    default: 1,
    comment: '1 = Active, 0 = Inactive/Soft Deleted',
  })
  status: number;

  @Column({
    type: 'varchar',
    length: 20,
    default: 'draft',
    comment: 'draft = pending review, approved = accepted, rejected = sent back',
  })
  reviewStatus: string;

  @Column({
    type: 'int',
    default: null,
  })
  reviewerId: number;

  @Column({
    type: 'varchar',
    default: null,
  })
  reviewerRemark: string;

  @Column({
    type: 'int',
    default: null,
  })
  termId: number;

  @Column({
    type: 'bigint',
    nullable: true,
  })
  createdBy: number;

  @Column({
    type: 'bigint',
    nullable: true,
  })
  updatedBy: number;

  @CreateDateColumn({
    type: 'timestamp',
  })
  createdAt: Date;

  @UpdateDateColumn({
    type: 'timestamp',
  })
  updatedAt: Date;

  @Column({
    type: 'text',
    nullable: true,
    comment: 'Instruction shown before the question',
  })
  instruction: string;

  @Column({
    type: 'text',
    nullable: true,
    comment:
      'Scenario, passage, case study, observation or context for the question',
  })
  stimulus: string;
}
