name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /root/solar_backend

            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

              git fetch origin
              git reset --hard origin/main

            yarn install

            yarn run build

            pm2 restart solar-backend
